apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master 
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: BACK-END
      app: redis-master
  template:
    metadata:
      labels:
        tier: BACK-END
        app: redis-master
    spec:
      containers:
      - name: master-redis-devops
        image: redis
        resources:
          requests:
             memory: "100Mi"
             cpu: "100m"
        ports:
        - containerPort: 6379
